title: Disclose SIDE Scraper
description: Custom scraper for side.developpement-durable.gouv.fr
instructions: ''
type: object
properties:
  run_name: 
    title: Run name
    type: string
    description: Name to identify this run among others on DocumentCloud's interface
  project:
    title: Project
    type: string
    description: >-
      The DocumentCloud project title or ID of the project the documents should
      be uploaded to.  If the project title does not exist, it will be created.
  access_level:
    title: Access level (public, private, organization)
    type: string
    default: private
  target_year:
    title: Year to scrape
    description: leave blank for current year
    type: integer
  upload_limit:
    title: Maximum number of documents to upload (per run)
    description: 0 for no limit
    type: integer
    default: 0
  dry_run:
    title: Dry run
    type: boolean
    description: If true, documents are not uploaded, and event data is not updated.
    default: true
# required: 
#   - project
categories: 
  - monitor
eventOptions:
  name: target_year
  events:
    - hourly
    - daily
    - weekly